apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-volume
provisioner: ebs.csi.aws.com
volumeBindingMode: Immediate
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: io1
  iopsPerGB: "50"
  encrypted: "true"
