apiVersion: v1
kind: Pod
metadata:
  name: my-aws-pod-ebd
spec:
  containers:
    - name: my-ebs-container
      image: busybox
      command: ["sleep", "36000"]
      volumeMounts:
        - name: my-volume
          mountPath: /ebs-mount-path
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: myclaim
