apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      location: bangalore
  template:
    metadata:
      labels:
        location: bangalore
    spec:
      containers:
        - name: myfirstapp
          image: venkaiahk/myapp #Version 2 of 
---
apiVersion: v1
kind: Service
metadata:
  name: electronic-service
spec:
  selector:
    location: bangalore   # Selects pods with the label app=myapp
  ports:
    - protocol: TCP
      port: 80       # The internal ClusterIP service port
      targetPort: 8080 # The port the application container listens on
      # nodePort: 31000 # Optional
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: mying
spec:
  rules:
  - host: electronic.net
    http:
      paths:
      - backend:
          service:
            name: electronic-service
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
