apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume-demo
  labels:
    purpose: demonstrate-command
spec:
  volumes:
  - name: myvolume
    emptyDir:
  containers:
  - name: command-demo-container-1
    image: busybox
    command: ["sleep"]
    args: ["100"]
    volumeMounts:
    - name: myvolume
      mountPath: /empty-dir-volumne



  - name: command-demo-container-2
    image: busybox
    command: ["sleep" , "100"]
    volumeMounts:
    - name: myvolume
      mountPath: /empty-dir-volume

