apiVersion: v1
kind: Pod
metadata:
  name: host-path-volume
spec:
  volumes:
  - name: my-hostpath-volume
    hostPath:
      path: /root/MyHostPath
  containers:
  - name: mycoatiner-1
    image: busybox
    command: ["sleep" , "200"]
    volumeMounts:
    - name: my-hostpath-volume
      mountPath: /hostpathvolume
