
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc # Name of the claim
spec:
  accessModes:
    - ReadWriteOnce # Request ReadWriteOnce access
  resources:
    requests:
      storage: 100Mi # Request 1 Gigabyte of storage
  storageClassName: local-path # Specify
