apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-india
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      purpose: deployment-concept
  template:
    metadata:
      labels:
        purpose: deployment-concept
    spec:
      containers:
        - name: rediss-image
          image: tomcat #Version 2 of the application
          
      nodeSelector:
        country: India

