apiVersion: v1
kind: Pod
metadata:
  name: sc-pod
spec:
  volumes:
    - name: my-sc-volume
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: my-sc-container
      image: busybox
      command: ["sleep","36000"]
      volumeMounts:
        - name: my-sc-volume
          mountPath: /local-path-sc
          
