apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sc-1
spec:
  selector:
    matchLabels:
      volume: storage-class-local-path
  storageClassName: local-path # Replace with your cluster's StorageClass name
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
