apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  volumes:
    - name: mypvc-volume
      persistentVolumeClaim:
        claimName: pvc
  containers:
  - name: mypvc-conatainer
    image: busybox
    command: ["sleep" , "300"]
    volumeMounts:
      - name: mypvc-volume
        mountPath: /mypvc-volume
