---
  apiVersion: v1
  kind: Pod
  metadata:
    name: res-f
    labels:
      app-name: flipkart
  spec:
#    selector:
 #     app-name: flipkart
    containers:
    - name: my-ubuntu
      image: httpd
      resources:
        requests:
          cpu: "250m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "500Mi"
    nodeSelector:
      app-name: flipkart-app
