apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
data:
  username: dmVua2FpYWgtRXVyb3Bl
  password: VmVua2FpYWhAMTIz
type: Opaque

---
apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
spec:
  volumes:
    - name: my-volume
      secret:
        secretName: my-secrets
  containers:
    - name: my-secret-container
      image: nginx
      volumeMounts:
        - name: my-volume
          mountPath: "/etc/my-secret-file"
  
