apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: venkaiah-app
  name: venkaiah-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: venkaiah-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: venkaiah-app
    spec:
      containers:
      - image: venkaiahk/myapp
        name: myapp
      
---
apiVersion: v1
kind: Service
metadata:
  name: venkaiah-app-service
spec:
  type: NodePort
  selector:
    app: venkaiah-app
  ports:
    - port: 8080



